import logging
from typing import List, Dict

logger = logging.getLogger(__name__)

# Curated list of common Swiss AVAM profession codes 
# Keys are AVAM codes (as strings), values are lists of normalized job titles in various languages.
# Note: These are representative codes. JobRoom API expects valid AVAM codes.
# 27114 is often generic IT, 27114004 is software engineer etc.
AVAM_MAPPING: Dict[str, List[str]] = {
    # Software Engineering & IT
    "27114004": [
        "software engineer", "softwareentwickler", "ingénieur logiciel", "sviluppatore software", 
        "software developer", "developer", "entwickler", "programmeur", "software", "programmer"
    ],
    "27114014": [
        "devops engineer", "devops-ingenieur", "devops", "site reliability engineer", "sre"
    ],
    "27114003": [
        "web developer", "webentwickler", "développeur web", "frontend developer", 
        "backend developer", "fullstack developer", "full stack", "web"
    ],
    "27111001": [
        "system administrator", "systemadministrator", "administrateur système", "sysadmin", 
        "it administrator", "system engineer", "it support"
    ],
    "27115001": [
        "data scientist", "data engineer", "datenwissenschaftler", "data analyst", "datenanalyst"
    ],
    "27113002": [
        "it project manager", "it projektleiter", "chef de projet it", "scrum master", "agile coach", "project manager"
    ],
    "27113003": [
        "it consultant", "it berater", "consultant en informatique", "business analyst", "consultant"
    ],
    "27114016": [
        "security engineer", "it security", "cyber security", "sicherheitsexperte", "security"
    ],
    "27114013": [
        "cloud engineer", "cloud architect", "aws engineer", "azure engineer", "cloud computing"
    ],

    # Finance & Management
    "33100": [
        "financial analyst", "finanzanalyst", "analyste financier", "finance"
    ],
    "33101": [
        "accountant", "buchhalter", "comptable", "controller", "controlling"
    ],
    "34101": [
        "sales manager", "sales", "verkauf", "account manager", "key account manager"
    ],
    "41103": [
        "hr manager", "human resources", "personalverantwortlicher", "recruiter", "talent acquisition"
    ],
    "61002": [
        "marketing manager", "marketing", "digital marketing"
    ]
}

class AVAMProfessionMapper:
    """
    Maps textual occupation titles (as generated by the LLM planner)
    into Swiss AVAM profession codes for the JobRoom API.
    """
    
    def __init__(self):
        self._cache = AVAM_MAPPING
        
    def resolve(self, title: str) -> List[str]:
        """
        Takes a job title/occupation string and returns a list of matching AVAM codes.
        If no match is found, returns an empty list.
        """
        if not title:
            return []
            
        normalized = title.lower().strip()
        matches = set()
        
        for code, aliases in self._cache.items():
            for alias in aliases:
                # Basic token intersection or substring matching
                # Check if the alias is in the title, or title in the alias
                if alias in normalized or normalized in alias:
                    matches.add(code)
                    
        result = list(matches)
        if result:
            logger.debug(f"Mapped occupation '{title}' to AVAM codes: {result}")
        else:
            logger.debug(f"No AVAM mapping found for occupation '{title}'")
            
        return result
        
avam_mapper = AVAMProfessionMapper()
