"""split_job_model_and_extend_profile

Revision ID: 4e50d54b9df1
Revises: 7b2a37169931
Create Date: 2026-03-24 21:39:57.557028
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e50d54b9df1'
down_revision: Union[str, None] = '7b2a37169931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_job_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=False),
    sa.Column('application_url', sa.String(), nullable=True),
    sa.Column('application_email', sa.String(), nullable=True),
    sa.Column('workload', sa.String(), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_query', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_job_id', name='uq_scraped_job_platform_id')
    )
    op.create_index(op.f('ix_scraped_jobs_company'), 'scraped_jobs', ['company'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_external_url'), 'scraped_jobs', ['external_url'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_id'), 'scraped_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_location'), 'scraped_jobs', ['location'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_platform'), 'scraped_jobs', ['platform'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_platform_job_id'), 'scraped_jobs', ['platform_job_id'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_title'), 'scraped_jobs', ['title'], unique=False)
    op.add_column('jobs', sa.Column('search_profile_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('scraped_job_id', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('distance_km', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_location'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_url'), table_name='jobs')
    op.create_index(op.f('ix_jobs_scraped_job_id'), 'jobs', ['scraped_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_search_profile_id'), 'jobs', ['search_profile_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'scraped_jobs', ['scraped_job_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'search_profiles', ['search_profile_id'], ['id'])
    op.drop_column('jobs', 'publication_date')
    op.drop_column('jobs', 'application_email')
    op.drop_column('jobs', 'jobroom_url')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'company')
    op.drop_column('jobs', 'url')
    op.drop_column('jobs', 'workload')
    op.drop_column('jobs', 'title')
    op.drop_column('jobs', 'source_query')
    op.drop_column('jobs', 'location')
    op.add_column('search_profiles', sa.Column('contract_type', sa.String(), nullable=True))
    op.add_column('search_profiles', sa.Column('max_queries', sa.Integer(), nullable=True))
    op.add_column('search_profiles', sa.Column('is_history', sa.Boolean(), nullable=True))
    op.add_column('search_profiles', sa.Column('is_stopped', sa.Boolean(), nullable=True))
    op.add_column('search_profiles', sa.Column('advanced_preferences', sa.Text(), nullable=True))
    op.add_column('search_profiles', sa.Column('max_occupation_queries', sa.Integer(), nullable=True))
    op.add_column('search_profiles', sa.Column('max_keyword_queries', sa.Integer(), nullable=True))
    op.add_column('search_profiles', sa.Column('cached_cv_summary', sa.Text(), nullable=True))
    op.add_column('search_profiles', sa.Column('cached_queries', sa.Text(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_column('users', 'supabase_id')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('supabase_id', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=1)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('search_profiles', 'cached_queries')
    op.drop_column('search_profiles', 'cached_cv_summary')
    op.drop_column('search_profiles', 'max_keyword_queries')
    op.drop_column('search_profiles', 'max_occupation_queries')
    op.drop_column('search_profiles', 'advanced_preferences')
    op.drop_column('search_profiles', 'is_stopped')
    op.drop_column('search_profiles', 'is_history')
    op.drop_column('search_profiles', 'max_queries')
    op.drop_column('search_profiles', 'contract_type')
    op.add_column('jobs', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('source_query', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('workload', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('url', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('company', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('jobs', sa.Column('jobroom_url', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('application_email', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('publication_date', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_search_profile_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scraped_job_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_url'), 'jobs', ['url'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index(op.f('ix_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.drop_column('jobs', 'distance_km')
    op.drop_column('jobs', 'scraped_job_id')
    op.drop_column('jobs', 'search_profile_id')
    op.drop_index(op.f('ix_scraped_jobs_title'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_platform_job_id'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_platform'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_location'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_id'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_external_url'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_company'), table_name='scraped_jobs')
    op.drop_table('scraped_jobs')
    # ### end Alembic commands ###
