"""Add ScrapedJob UniqueConstraint

Revision ID: aa38af1be029
Revises: b3c4d5e6f7a8
Create Date: 2026-03-24 13:49:41.398436
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa38af1be029'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_jobs',
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_job_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=False),
    sa.Column('application_url', sa.String(), nullable=True),
    sa.Column('application_email', sa.String(), nullable=True),
    sa.Column('workload', sa.String(), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('source_query', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_job_id', name='uq_scraped_job_platform_id')
    )
    op.create_index(op.f('ix_scraped_jobs_company'), 'scraped_jobs', ['company'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_external_url'), 'scraped_jobs', ['external_url'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_id'), 'scraped_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_location'), 'scraped_jobs', ['location'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_platform'), 'scraped_jobs', ['platform'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_platform_job_id'), 'scraped_jobs', ['platform_job_id'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_title'), 'scraped_jobs', ['title'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('search_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cv_content', sa.Text(), nullable=True),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('search_strategy', sa.Text(), nullable=True),
    sa.Column('location_filter', sa.String(), nullable=True),
    sa.Column('workload_filter', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('posted_within_days', sa.Integer(), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('scrape_mode', sa.String(), nullable=True),
    sa.Column('max_queries', sa.Integer(), nullable=True),
    sa.Column('is_history', sa.Boolean(), nullable=True),
    sa.Column('is_stopped', sa.Boolean(), nullable=True),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=True),
    sa.Column('schedule_interval_hours', sa.Integer(), nullable=True),
    sa.Column('last_scheduled_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('advanced_preferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_profiles_id'), 'search_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_search_profiles_user_id'), 'search_profiles', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_profile_id', sa.Integer(), nullable=True),
    sa.Column('scraped_job_id', sa.Integer(), nullable=False),
    sa.Column('is_scraped', sa.Boolean(), nullable=True),
    sa.Column('affinity_score', sa.Float(), nullable=True),
    sa.Column('affinity_analysis', sa.Text(), nullable=True),
    sa.Column('worth_applying', sa.Boolean(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scraped_job_id'], ['scraped_jobs.id'], ),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_scraped_job_id'), 'jobs', ['scraped_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_search_profile_id'), 'jobs', ['search_profile_id'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_search_profile_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scraped_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_search_profiles_user_id'), table_name='search_profiles')
    op.drop_index(op.f('ix_search_profiles_id'), table_name='search_profiles')
    op.drop_table('search_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scraped_jobs_title'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_platform_job_id'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_platform'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_location'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_id'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_external_url'), table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_company'), table_name='scraped_jobs')
    op.drop_table('scraped_jobs')
    # ### end Alembic commands ###
